name: Build Windows

on:
  push:
    paths:
      - "**/workflows/build_windows.yml"
      - "**/Source/**"
      - "**/Tests/**"
      - "**/ThirdParty/**"
      - "**/CMakeLists.txt"
      - "**/.gitmodules"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    steps:

    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE --parallel 4

    - name: Test Lua 5.1
      working-directory: ${{runner.workspace}}/build/Tests/Release
      shell: bash
      run: |
        ./LuaBridgeTests51.exe
        ./LuaBridgeTests51Noexcept.exe

    - name: Test Lua 5.2
      working-directory: ${{runner.workspace}}/build/Tests/Release
      shell: bash
      run: |
        ./LuaBridgeTests52.exe
        ./LuaBridgeTests52Noexcept.exe

    - name: Test Lua 5.3
      working-directory: ${{runner.workspace}}/build/Tests/Release
      shell: bash
      run: |
        ./LuaBridgeTests53.exe
        ./LuaBridgeTests53Noexcept.exe

    - name: Test Lua 5.4
      working-directory: ${{runner.workspace}}/build/Tests/Release
      shell: bash
      run: |
        ./LuaBridgeTests54.exe
        ./LuaBridgeTests54Noexcept.exe

    #- name: Test LuaJIT
    #  working-directory: ${{runner.workspace}}/build/Tests/Release
    #  shell: bash
    #  run: ./LuaBridgeTestsLuaJIT.exe

    - name: Test LuaJIT - No Exceptions
      working-directory: ${{runner.workspace}}/build/Tests/Release
      shell: bash
      run: |
        ./LuaBridgeTestsLuaJITNoexcept.exe

    - name: Test Luau
      working-directory: ${{runner.workspace}}/build/Tests/Release
      shell: bash
      run: ./LuaBridgeTestsLuau.exe
