name: Windows

on:
  push:
    paths:
      - "**/workflows/build_windows.yml"
      - "**/Source/**"
      - "**/Tests/**"
      - "**/ThirdParty/**"
      - "**/CMakeLists.txt"
      - "**/.gitmodules"
      - "!**/*.md"
      - "!**/*.txt"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  BUILD_TYPE: Release

jobs:
  lua:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        lua:
          - { version: "5.1", suffix: "51" }
          - { version: "5.2", suffix: "52" }
          - { version: "5.3", suffix: "53" }
          - { version: "5.4", suffix: "54" }
          - { version: "5.5", suffix: "55" }

    steps:

    - uses: actions/checkout@v6
      with:
        submodules: true

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build Lua ${{ matrix.lua.version }}
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: |
        cmake --build . --config $BUILD_TYPE --parallel 4 --target \
          LuaBridgeTests${{ matrix.lua.suffix }} \
          LuaBridgeTests${{ matrix.lua.suffix }}Reflect \
          LuaBridgeTests${{ matrix.lua.suffix }}LuaC \
          LuaBridgeTests${{ matrix.lua.suffix }}Noexcept \
          LuaBridgeTests${{ matrix.lua.suffix }}ReflectNoexcept \
          LuaBridgeTests${{ matrix.lua.suffix }}LuaCNoexcept

    - name: Test Lua ${{ matrix.lua.version }}
      working-directory: ${{runner.workspace}}/build/Tests/Release
      shell: bash
      run: |
        ./LuaBridgeTests${{ matrix.lua.suffix }}.exe
        ./LuaBridgeTests${{ matrix.lua.suffix }}Reflect.exe
        ./LuaBridgeTests${{ matrix.lua.suffix }}LuaC.exe
        ./LuaBridgeTests${{ matrix.lua.suffix }}Noexcept.exe
        ./LuaBridgeTests${{ matrix.lua.suffix }}ReflectNoexcept.exe
        ./LuaBridgeTests${{ matrix.lua.suffix }}LuaCNoexcept.exe

  luajit:
    runs-on: windows-latest
    steps:

    - uses: actions/checkout@v6
      with:
        submodules: true

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build LuaJIT
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: |
        cmake --build . --config $BUILD_TYPE --parallel 4 --target \
          LuaBridgeTestsLuaJIT \
          LuaBridgeTestsLuaJITReflect \
          LuaBridgeTestsLuaJITNoexcept \
          LuaBridgeTestsLuaJITReflectNoexcept

    - name: Test LuaJIT
      working-directory: ${{runner.workspace}}/build/Tests/Release
      shell: bash
      run: |
        ./LuaBridgeTestsLuaJIT.exe
        ./LuaBridgeTestsLuaJITReflect.exe
        ./LuaBridgeTestsLuaJITNoexcept.exe
        ./LuaBridgeTestsLuaJITReflectNoexcept.exe

  luau:
    runs-on: windows-latest
    steps:

    - uses: actions/checkout@v6
      with:
        submodules: true

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build Luau
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: |
        cmake --build . --config $BUILD_TYPE --parallel 4 --target \
          LuaBridgeTestsLuau \
          LuaBridgeTestsLuauReflect

    - name: Test Luau
      working-directory: ${{runner.workspace}}/build/Tests/Release
      shell: bash
      run: |
        ./LuaBridgeTestsLuau.exe
        ./LuaBridgeTestsLuauReflect.exe

  ravi:
    runs-on: windows-latest
    steps:

    - uses: actions/checkout@v6
      with:
        submodules: true

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build Ravi
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: |
        cmake --build . --config $BUILD_TYPE --parallel 4 --target \
          LuaBridgeTestsRavi \
          LuaBridgeTestsRaviReflect

    - name: Test Ravi
      working-directory: ${{runner.workspace}}/build/Tests/Release
      shell: bash
      run: |
        cp ../ravi/Release/libravi.dll .
        ./LuaBridgeTestsRavi.exe
